# Generated by ariadne-codegen
# Source: queries/series-state

from typing import Any, Dict

from .base_client import BaseClient
from .series_draft_summary import SeriesDraftSummary
from .series_games import SeriesGames


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def series_draft_summary(self, series_id: str, **kwargs: Any) -> SeriesDraftSummary:
        query = gql(
            """
            query SeriesDraftSummary($seriesID: ID!) {
              seriesState(id: $seriesID) {
                id
                finished
                valid
                games {
                  id
                  draftActions {
                    id
                    type
                    sequenceNumber
                    drafter {
                      id
                      type
                    }
                    draftable {
                      id
                      type
                      name
                    }
                  }
                  sequenceNumber
                  teams {
                    __typename
                    id
                    name
                    side
                    won
                    players {
                      __typename
                      id
                      name
                      character {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"seriesID": series_id}
        response = self.execute(
            query=query,
            operation_name="SeriesDraftSummary",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return SeriesDraftSummary.model_validate(data)

    def series_games(self, series_id: str, **kwargs: Any) -> SeriesGames:
        query = gql(
            """
            query SeriesGames($seriesID: ID!) {
              seriesState(id: $seriesID) {
                id
                finished
                valid
                games {
                  id
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"seriesID": series_id}
        response = self.execute(
            query=query, operation_name="SeriesGames", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SeriesGames.model_validate(data)
